Projects/question_answer/qna/main/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, session, abort
#from qna.db import get_db
from qna import db
from qna.users.utils import get_current_user
import datetime

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
@main_bp.route('/home')
def home():
    #db = get_db()
    try:
        db.execute(
            'SELECT * FROM questions WHERE answer_text IS NOT NULL')
        questions_ans = db.fetchall()

        db.execute('SELECT * FROM questions WHERE answer_text IS NULL')
        questions_no_ans = db.fetchall()

        db.execute(
            'SELECT username FROM users INNER JOIN questions ON users.id=questions.asked_by_id WHERE answer_text IS NULL')
        no_ans_asked_by = db.fetchall()

        db.execute(
            'SELECT username FROM users INNER JOIN questions ON users.id=questions.asked_by_id WHERE answer_text IS NOT NULL')
        ans_asked_by = db.fetchall()

        db.execute(
            'SELECT username FROM users INNER JOIN questions ON users.id=questions.expert_id')
        ans_answered_by = db.fetchall()

        ans_pretty_dates, no_ans_pretty_dates = [], []
        for i in range(len(questions_ans)):
            try:
                ans_pretty_dates.append(datetime.datetime.strptime(
                    str(questions_ans[i]['time']), '%Y-%m-%d %H:%M:%S').strftime('%B %d, %Y' + ' at ' + '%I:%M %p'))
            except Exception as e:
                raise abort("Error: " + str(e))

        for i in range(len(questions_no_ans)):
            try:
                no_ans_pretty_dates.append(datetime.datetime.strptime(
                    str(questions_no_ans[i]['time']), '%Y-%m-%d %H:%M:%S').strftime('%B %d, %Y' + ' at ' + '%I:%M %p'))
            except Exception as e:
                return "Error: " + str(e)

    except:
        abort(500)
    return render_template('home.html', questions_ans=questions_ans, questions_no_ans=questions_no_ans,
                           no_ans_asked_by=no_ans_asked_by, ans_asked_by=ans_asked_by,
                           no_ans_pretty_dates=no_ans_pretty_dates, ans_pretty_dates=ans_pretty_dates,
                           ans_answered_by=ans_answered_by)


@main_bp.route('/about')
def about():
    return render_template('about.html')

Projects/question_answer/qna/questions/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, session, flash, abort
#from qna.db import get_db
from qna import db
import datetime

questions_bp = Blueprint('questions', __name__)


@questions_bp.route('/ask', methods=['GET', 'POST'])
def ask():

    if not session.get('id', None):
        abort(403)

    if request.method == "POST":
        #db = get_db()
        question_text = request.form['question']

        db.execute('INSERT INTO questions (question_text, asked_by_id) VALUES(%s, %s)', (
                   question_text, session['id'],))

        flash("Question asked successfully", "success")
        return redirect(url_for('main.home'))

    return render_template("ask.html")


@questions_bp.route('/answer', methods=['GET', 'POST'])
def answer():

    if session.get('expert', None) != 1:
        abort(403)

    #db = get_db()
    db.execute('SELECT * FROM questions WHERE answer_text IS NULL')
    questions_no_ans = db.fetchall()

    db.execute(
        'SELECT username FROM users INNER JOIN questions ON users.id=questions.asked_by_id WHERE answer_text IS NULL')
    asked_by = db.fetchall()

    pretty_dates = []
    for i in range(len(questions_no_ans)):
        pretty_dates.append(datetime.datetime.strptime(
            str(questions_no_ans[i]['time']), '%Y-%m-%d %H:%M:%S').strftime('%B %d, %Y' + ' at ' + '%I:%M %p'))

    return render_template('awaiting_questions.html', questions_no_ans=questions_no_ans, pretty_dates=pretty_dates, asked_by=asked_by)


@questions_bp.route('/answer/<int:id>', methods=['GET', 'POST'])
def answer_specific(id):

    if session.get('expert', None) != 1:
        abort(403)

    db = get_db()
    db.execute(
        'SELECT * FROM questions WHERE id=%s', (id,))
    question = db.fetchone()

    db.execute('SELECT username FROM users WHERE users.id=%s',
               (question['asked_by_id'],))
    asked_by = db.fetchone()[0]
    if request.method == "POST":
        answer = request.form['answer']
        db.execute(
            'UPDATE questions SET answer_text=%s, expert_id=%s WHERE id=%s', [answer, session['id'], question['id']])
        flash("Answer submitted successfully", "success")
        return redirect(url_for('main.home'))

    return render_template('answer.html', question=question, asked_by=asked_by)

Projects/question_answer/qna/users/routes.py
from email.policy import default
from flask import Blueprint, request, redirect, render_template, url_for, session, flash, abort
from werkzeug.security import generate_password_hash, check_password_hash
from qna.db import get_db
from qna.users.utils import get_current_user
import time

users_bp = Blueprint('users', __name__)


@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        db = get_db()

        username = request.form['username']
        password = request.form['password']

        db.execute(
            'SELECT * FROM users WHERE username = %s', (username,))
        user = db.fetchone()

        if user is None:
            flash('Invalid username or password', 'danger')
            return redirect(url_for('users.login'))

        db.execute(
            'SELECT password FROM users WHERE username=%s', (username,))
        hashed_password = db.fetchone()[0]
        if check_password_hash(hashed_password, password):
            session['username'] = user['username']
            session['id'] = user['id']
            session['email'] = user['email']
            session['admin'] = user['admin']
            session['expert'] = user['expert']

            flash('Successfully logged in', 'success')
        else:
            flash('Incorrect username or password', 'danger')

    if session.get('id', None):
        return redirect(url_for('main.home'))
    return render_template('login.html')


@users_bp.route('/logout/<int:updated>', methods=['GET', 'POST'])
def logout(updated=0):
    print(updated)

    username = session.pop('username', None)
    session.clear()
    referrer = request.referrer

    if username:

        if 'account' in referrer and updated == 1:
            flash(
                'Successfully updated account credentials. Please log in again.', 'success')
            return redirect(url_for('users.login'))
        else:
            flash('Successfully logged out', 'success')
    return redirect(url_for('main.home'))


@users_bp.route('/register', methods=['GET', 'POST'])
def register():
    if session.get('id', None):
        return redirect(url_for('main.home'))

    if request.method == "POST":
        db = get_db()
        username = request.form['username']
        hashed_password = generate_password_hash(
            request.form['password'], method='sha256')
        email = request.form['email']
        try:
            db.execute(
                'SELECT * FROM users WHERE username = %s', (username,))
            username_exists = db.fetchone()
            if username_exists:
                flash('Username already exists', 'danger')
                raise Exception('Username already exists')

            db.execute('INSERT INTO users (username, password, email, expert, admin) VALUES(%s, %s, %s, FALSE, FALSE)',
                       (username, hashed_password, email,))

            flash('Successfully registered', 'success')
        except:
            flash('Registration failed, please try again with different values', 'danger')
    return render_template('register.html')


@users_bp.route('/users')
def users():
    db = get_db()
    db.execute('SELECT * FROM users WHERE admin=FALSE')
    users = db.fetchall()

    db.execute('SELECT * FROM users WHERE admin=TRUE')
    admins = db.fetchall()

    db.execute('SELECT * FROM users WHERE expert=TRUE')
    experts = db.fetchall()
    return render_template('users.html', admins=admins, users=users, experts=experts)


@users_bp.route('/account/<int:id>', methods=['GET', 'POST'])
def account(id):
    if session.get('id', None) != id:
        abort(403)

    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']

        try:
            db = get_db()
            db.execute('SELECT * FROM users WHERE id = %s', (id,))
            curr_user = db.fetchone()

            db.execute('SELECT * FROM users WHERE username = %s', (username,))
            new_username = db.fetchone()
            if new_username != None and new_username['id'] != id:
                flash('New username already exists', 'danger')
                return redirect(url_for('users.account', id=id))

            db.execute('SELECT * FROM users WHERE email = %s', (email,))
            new_email = db.fetchone()
            if new_email != None and new_email['email'] != curr_user['email']:
                flash('New email already exists', 'danger')
                return redirect(url_for('users.account', id=id))

            if(len(password) > 0):
                password = generate_password_hash(
                    password, method='sha256')
            else:
                password = curr_user['password']

            db.execute('UPDATE users SET username = %s, password = %s, email = %s WHERE id = %s',
                       (username, password, email, id,))

            return redirect(url_for('users.logout', updated=1))

        except Exception as e:
            return e, 500

    return render_template('account.html')

Projects/question_answer/qna/templates/about.html
{% extends 'layout.html' %}
{% block title %}Users{% endblock title %}
{% block content %}
<div class="home-wrap no-border">
    <h1>Created by <a style="text-decoration:none; color:#ec6611" href="https://www.facebook.com/toaxoy">Tevfik Oguzhan Aksoy &#129409</a></h1> 
    <h1>Reach me out on:</h1>
    <ul class="about-ul">
        <h1><li><a style="text-decoration:none; color:#ec6611" href="https://www.linkedin.com/in/AxoyTO/">LinkedIn</a></li></h1>
        <h1><li><a style="text-decoration:none; color:#ec6611" href="https://www.github.com/AxoyTO/">GitHub</a></li></h1>
        <h1><li><a style="text-decoration:none; color:#ec6611" href="https://vk.com/toaxoy">VKontakte</a></li></h1>
        <h1><li><a style="text-decoration:none; color:#ec6611" href="https://www.instagram.com/toaksoy/">Instagram</a></li></h1>
    </ul>
</div>
{% endblock content %}

Projects/question_answer/qna/templates/account.html
{% extends 'layout.html' %}
{% block title %}Account{% endblock title %}
{% block content %}
    <div class="acc-wrap">
        <div class="acc-container">
            <div class="acc-title">
                {{session['username']}}'s Page
            </div>
            <div class="acc-form-container">
                <form action="" method="POST">
                    <div class="acc-form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" maxlength="12" id="username" value="{{session['username']}}">
                    </div>
                    <div class="acc-form-group">
                        <label for="password">Password</label>
                        <input type="password" maxlength="10" name="password" id="password">
                    </div>
                    <div class="acc-form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" value="{{session['email']}}">
                    </div>
                    <div class="button-group">
                        <input class="form-button" type="submit" value="Update">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Projects/question_answer/qna/templates/answer.html
{% extends 'layout.html' %}
{% block title %}Answer{% endblock title %}
{% block content %}
    <div class="question-wrap">
        <div class="question-form">
            <form action="" method="POST" id="qform">
                <legend>Answer the Question</legend>
                <div class="question-group">
                    <label for="question">Question from <span style="color:#ec6611">{{asked_by}}</span></label>
                    <textarea class="disabled-text" name="question" id="question" cols="20" rows="5" readonly>{{question.question_text}}</textarea>
                    
                    <label for="answer">Your answer</label>
                    <textarea spellcheck="true" autofocus="true" minlength="10" maxlength="600" placeholder="Enter your answer here" namerows="5" cols="60" name="answer" id="answer" form="qform" required></textarea>
                    <input type="checkbox" name="terms" id="terms" required checked>
                    <label for="terms">I hereby confirm that this answer is related to the question and does not contain anything that may include any kind of illegal activity.</label>
                    <input type="submit" name="submit" value="Answer">
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

Projects/question_answer/qna/templates/ask.html
{% extends 'layout.html' %}
{% block title %}Ask Question{% endblock title %}

{% block content %}
<div class="question-wrap">
    <div class="question-form">
        <form action="" method="POST" id="qform">
            <legend>Question</legend>
            <div class="question-group">
                <label for="question">What's your question?</label>
                <textarea spellcheck="true" autofocus="true" minlength="12" maxlength="300" placeholder="Enter your question here" namerows="5" cols="60" name="question" id="question" form="qform" required></textarea>
                <input type="checkbox" name="terms" id="terms" required checked>
                <label for="terms">I hereby confirm that this question is asked by me and does not contain anything that may include any kind of illegal activity.</label>
                <input type="submit" name="submit" value="Ask">
            </div>
        </form>
    </div>
</div>

{% endblock content %}

Projects/question_answer/qna/templates/awaiting_questions.html
{% extends 'layout.html' %}
{% block title %}Answer{% endblock title %}
{% block content %}
    <div class="home-wrap">
        <div class="home-header">
            <h1>Questions awaiting an answer</h1>
        </div>
        <div class="question-wrapper">
            {% for question in questions_no_ans %}
                <div class="question-content">
                    <a class="question-link" href="{{ url_for('questions.answer_specific', id=question.id) }}">
                        <div class="question-header">
                            Question №: {{question.id}}
                            <div class="question-asker">
                                from {{asked_by[loop.index0]['username']}}
                            </div>
                            <div class="question-time">
                                {{pretty_dates[loop.index0]}}
                            </div>
                        </div>
                    </a>
                    <div class="question-text">
                        {{question.question_text}}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

Projects/question_answer/qna/templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
    <div class="home-wrap">
        <div class="home-header">
            <h1>Answered questions</h1>
        </div>
        <div class="question-wrapper">
            {% for question in questions_ans %}
                <div class="question-content">
                    <div class="question-header">
                        Question №: {{question.id}}
                        <div class="question-asker">
                            from {{ans_asked_by[loop.index0]['username']}}
                        </div>
                        <div class="question-time">
                            {{ans_pretty_dates[loop.index0]}}
                        </div>
                    </div>
                    <div class="question-text">
                        {{question.question_text}}
                    </div>
                    <hr>
                    <div class="answer-text">
                        <p><span style="font-weight:600; color:#ec6611">Answer by {{ans_answered_by[loop.index0]['username']}}:</span> {{question.answer_text}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="home-wrap">
        <div class="home-header">
            <h1>Questions awaiting an answer</h1>
        </div>
        <div class="question-wrapper">
            {% for question in questions_no_ans %}
                <div class="question-content">
                    <div class="question-header">
                        Question №: {{question.id}}
                        <div class="question-asker">
                            from {{no_ans_asked_by[loop.index0]['username']}}
                        </div>
                        <div class="question-time">
                            {{no_ans_pretty_dates[loop.index0]}}
                        </div>
                    </div>
                    <div class="question-text">
                        {{question.question_text}}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

Projects/question_answer/qna/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <title>Q&A | {% block title %}{% endblock title %}</title>
</head>
<body>
    <nav>
        <div class="nav-container">
            <img src="{{ url_for('static', filename='img/qalogo.png') }}" alt="Logo of QA">
            <ul>
                <li class="fl ml-2"><a href="{{ url_for('main.home') }}">Home</a></li>
                <li class="fl"><a href="{{ url_for('main.about') }}">About</a></li>
                <li class="fl"><a href="{{ url_for('users.users') }}">Users</a></li>
                {% if session['username'] %}
                    <li class="fl"><a href="{{ url_for('questions.ask') }}">Ask Question</a></li>
                {% endif %}
                {% if session['expert'] %}
                    <li class="fl"><a href="{{ url_for('questions.answer') }}">Answer Questions</a></li>
                {% endif %}
            </ul>
            <ul class="user-l">
                {% if not session['id'] %}
                    <li class="fl"><a href="{{ url_for('users.register') }}">Register</a></li>
                    <li class="fl"><a href="{{ url_for('users.login') }}">Login</a></li>
                {% else %}
                    <li class="fl"><a href="{{ url_for('users.account', id=session['id']) }}">Account</a></li>
                    <li class="fl"><a href="{{ url_for('users.logout', updated=0) }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages %}
            {% for category, message in messages %}
            <div id="hideMe">
                <div class="meter alert alert-{{category}}">
                    {{message}}<span><span class="progress-{{category}}"></span></span>
                </div>
                
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock content %}
</body>
</html>

Projects/question_answer/qna/templates/login.html
{% extends 'layout.html' %} {% block title %}Login{% endblock title %} {% block
content %}
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-1" type="radio" name="tab" class="sign-in" checked /><label
      for="tab-1"
      class="tab"
      >Login</label
    >
    <div class="login-form">
      <form action="" method="POST">
        <div class="sign-in-htm">
          <div class="group">
            <label for="user" class="label">Username</label>
            <input name="username" maxlength="12" id="user" type="text" class="input" placeholder="Username" required/>
          </div>
          <div class="group">
            <label for="pass" class="label">Password</label>
            <input name="password" maxlength="10" id="pass" type="password" class="input" data-type="password" placeholder="Password" required/>
          </div>
          <div class="group">
            <input type="submit" class="button" value="Login"/>
          </div>
          <div class="hr"></div>
          <div class="foot-lnk">
            <a style="width: 35%" href="#forgot">Forgot Password?</a>
            <a href="{{ url_for('users.register') }}">Register</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

Projects/question_answer/qna/templates/register.html
{% extends 'layout.html' %} {% block title %}Register{% endblock title %} {%
block content %}
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-2" type="radio" name="tab" class="sign-up" checked /><label
      for="tab-2"
      class="tab"
      >Register</label
    >
    <div class="login-form">
      <form action="" method="POST">
        <div class="sign-up-htm">
          <div class="group">
            <label for="user" class="label">Username</label>
            <input name="username" oninput="javascript: if (this.value.length > this.maxlength) this.value = this.value.slice(0, this.maxLength);" maxlength="10" id="user" type="text" class="input" placeholder="Name"/>
          </div>
          <div class="group">
            <label for="pass" class="label">Password</label>
            <input name="password" maxlength="10" id="pass" type="password" class="input" data-type="password" placeholder="Password"/>
          </div>
          <div class="group">
            <label for="pass" class="label">Email Address</label>
            <input name="email" id="pass" type="email" class="input" placeholder="Email"/>
          </div>
          <div class="group">
            <input type="submit" class="button" value="Register" />
          </div>
          <div class="hr"></div>
          <div class="foot-lnk">
            Already a Member?
            <a style="display: inline" href="{{ url_for('users.login') }}"
              >Login</a
            >
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Projects/question_answer/qna/templates/users.html
{% extends 'layout.html' %}
{% block title %}Users{% endblock title %}
{% block content %}
<div class="users-wrap no-border">
    <div class="users-container">
        <div class="users-header">
            <span>&#x1F451 Admins</span>
        </div>
        <ul class="users-list">
            {% for admin in admins %}
                <li>
                    {{admin.username}}
                    {% if admin.expert %}
                        <input class="expert-ic" type="text" name="expert" id="expert" value="EXPERT" disabled/>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="users-container">
        <div class="users-header">
            Users  
        </div>
        <ul class="users-list">
            {% for user in users %}
                <li>
                    {{user.username}}
                    {% if user.expert %}
                        <input class="expert-ic" type="text" name="expert" id="expert" value="EXPERT" disabled/>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}