Projects/flask-blog/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    announcement = BooleanField('Announcement')

    submit = SubmitField('Post')


class SortPostsForm(FlaskForm):
    options = [('date_posted_new', 'Date posted (Newest first)'),
               ('date_posted_old', 'Date posted (Oldest first)'),
               ('title', 'Title'),
               ('user', 'User'),
               ('priority', 'Priority')]
    sort_by = SelectField('Sort posts by:', choices=options)
    submit = SubmitField('Sort')

Projects/flask-blog/flaskblog/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, ValidationError, SubmitField, BooleanField, FileField
from wtforms.validators import Length, DataRequired, EqualTo, Email
from flaskblog.models import User
from flask_login import current_user


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=2)])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password', message="Password must match")])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                f'Username {username.data} already exists. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                f'Email {email.data} already exists. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[
        DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[
        FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    f'Username {username.data} already exists. Please choose a different one.')
        # else:
        #     raise ValidationError(f'Please choose a different username than your current one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    f'Email {email.data} already exists. Please choose a different one.')
        # else:
        #     raise ValidationError('Please choose a different email than your current one.')


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                'There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

Projects/flask-blog/flaskblog/main/routes.py
from flaskblog.models import Post
from flask import render_template, request, Blueprint
from flaskblog.posts.forms import SortPostsForm

main_bp = Blueprint('main', __name__)


@main_bp.route("/", methods=['GET', 'POST'])
@main_bp.route("/home", methods=['GET', 'POST'])
def home():
    page = request.args.get("page", 1, type=int)
    posts = Post.query.order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)
    form = SortPostsForm()
    if form.sort_by.data == "date_posted_new":
        posts = Post.query.order_by(
            Post.date_posted.desc()).paginate(page=page, per_page=5)
    elif form.sort_by.data == "date_posted_old":
        posts = Post.query.order_by(
            Post.date_posted.asc()).paginate(page=page, per_page=5)
    elif form.sort_by.data == "title":
        posts = Post.query.order_by(
            Post.title.asc()).paginate(page=page, per_page=5)
    elif form.sort_by.data == "user":
        posts = Post.query.order_by(
            Post.user_id.asc()).paginate(page=page, per_page=5)
    elif form.sort_by.data == "priority":
        posts = Post.query.order_by(
            Post.is_announcement.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts, form=form)


@main_bp.route("/about", endpoint="about")
def about():
    return render_template("about.html")

Projects/flask-blog/flaskblog/posts/routes.py
from flask import (render_template, request, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import login_required, current_user
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts_bp = Blueprint('posts', __name__)


@posts_bp.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user,
            is_announcement=form.announcement.data
        )
        db.session.add(post)
        db.session.commit()
        flash("Successfully created a new post!", "success")
        return redirect(url_for("main.home"))

    return render_template(
        "create_post.html", title="New Post", form=form, legend="Create a new post"
    )


@posts_bp.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title="Update Post", post=post)


@posts_bp.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and current_user.is_admin == False:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.is_announcement = form.announcement.data
        print(form.announcement.data, post.is_announcement)
        db.session.commit()
        flash("Successfully updated the post!", "success")
        return redirect(url_for("posts.post", post_id=post.id))

    form.title.data = post.title
    form.content.data = post.content
    form.announcement.data = post.is_announcement
    return render_template(
        "create_post.html",
        title="Update Post",
        form=form,
        post=post,
        legend="Update post",
    )


@posts_bp.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and current_user.is_admin == False:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Successfully deleted the post!", "success")
    return redirect(url_for("main.home"))


@posts_bp.route('/announcements')
def announcements():
    posts = Post.query.filter_by(is_announcement=True).paginate(per_page=5)
    return render_template('announcements.html', posts=posts)

Projects/flask-blog/flaskblog/users/routes.py
from flask import Blueprint, redirect, request, url_for, render_template, flash
from flask_login import current_user, login_user, login_required, logout_user
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.users.forms import (
    RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from flaskblog import db, bcrypt
from flaskblog.models import User, Post


users_bp = Blueprint('users', __name__)


@users_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created! You are now able to log in.", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash(f"Successfully logged in as {user.username}", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login failed. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form)


@users_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users_bp.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated successfully!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        "static", filename=f"profile_pics/{current_user.image_file}")
    return render_template(
        "account.html", title="Account", img_file=image_file, form=form
    )


@users_bp.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.date_posted.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_posts.html", posts=posts, user=user)


@users_bp.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users_bp.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)

    if not user:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template("reset_token.html", title="Reset Password", form=form)


@users_bp.route('/users', endpoint='users')
def users():
    users = User.query.filter_by(is_admin=False).order_by(
        User.username.asc()).paginate(per_page=15)
    admins = User.query.filter_by(is_admin=True).order_by(User.username.asc())
    return render_template('users.html', users=users, admins=admins)

Projects/flask-blog/flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
    <p>Created by Tevfik Oguzhan Aksoy.</p>
    <p>
        <a href="https://www.github.com/AxoyTO">GitHub</a></br>
        <a href="https://www.linkedin.com/in/axoyto/">LinkedIn</a>
    </p>
{% endblock content %}

Projects/flask-blog/flaskblog/templates/announcements.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              {% if post.author.is_admin %}
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">
                  {{ post.author.username }}
                  <small class="text-muted">
                    <input type="text" class="readonly" value="Admin" id="noselect" disabled></a>
                  </small>
              {% else %}
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }} </a>              
              {% endif %}
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y, %H:%M:%S') }}
                {% if post.is_announcement %}
                  <input type="text" class="readonly" id="noselect" value="Announcement" disabled>
                {% endif %}
              </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('main.home', page=page_num) }}">{{page_num}}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('main.home', page=page_num) }}">{{page_num}}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
    {% endfor %}
{% endblock content %}

Projects/flask-blog/flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              {% if post.author.is_admin %}
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">
                  {{ post.author.username }}
                  <small class="text-muted">
                    <input type="text" class="readonly" value="Admin" id="noselect" disabled></a>
                  </small>
              {% else %}
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }} </a>              
              {% endif %}
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y, %H:%M:%S') }}
                {% if post.is_announcement %}
                  <input type="text" class="readonly" id="noselect" value="Announcement" disabled>
                {% endif %}
              </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <span class="article-content">{{ post.content|truncate(250, True, end='...') }}</span>
            {% if post.content|length > 250 %}
              <a href="{{ url_for('posts.post', post_id=post.id) }}" class="link-info">Read More</a>
            {% endif %}
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('main.home', page=page_num) }}">{{page_num}}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('main.home', page=page_num) }}">{{page_num}}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
    {% endfor %}
{% endblock content %}
{% block sort %}
  <div class="form-group">
    <form action="" id="form" method="POST" class="selectform">
      {{form.hidden_tag()}}
      {{form.sort_by.label('Sort by:')}}
      {{form.sort_by(class="form-control")}}
      {{form.submit(class="btn btn-outline-info btn-sm mt-2")}}      
      </form>
  </div>
{% endblock sort %}

Projects/flask-blog/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="jquery-3.6.0.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
              <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-ite nav-link" href="{{url_for('posts.create_post')}}">Create a New Post</a>
                <a class="nav-ite nav-link" href="{{url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true)%}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Sidebar</h3>
            <p class='text-muted'>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('posts.announcements') }}">Announcements</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('users.users') }}">All Users</a></li>
                <li class="list-group-item list-group-item-light">{% block sort %}{% endblock sort %}</li>              
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</body>
</html>

Projects/flask-blog/flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{form.email.label(class="form=control-label")}}
                    
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class="form=control-label")}}

                    {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{form.password(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
                <small class="text-muted">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Your Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

Projects/flask-blog/flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}
          {% if post.author.is_admin %}
          <small class="text-muted">
            <input type="text" value="Admin" class="readonly" disabled>
          </small>
          {% endif %}
        </a>
        <small class="text-muted">
          {{ post.date_posted.strftime('%d-%m-%Y, %H:%M') }}
          {% if post.is_announcement %}
            <input type="text" class="readonly" value="Announcement" disabled>
          {% endif %}
        </small>
        {% if post.author == current_user or current_user.is_admin%}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Projects/flask-blog/flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{form.email.label(class="form=control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                         {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock content %}

Projects/flask-blog/flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{posts.total}})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}
                {% if post.author.is_admin %}
                  <small><input type="text" class="readonly" value="Admin", disabled></small>
                {% endif %}
              </a>
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y, %H:%M:%S') }}
                {% if post.is_announcement %}
                  <input type="text" class="readonly" value="Announcement" disabled>
                {% endif %}
              </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncate(250, True, end='...') }}</p>
            {% if post.content|length > 250 %}
              <a href="{{ url_for('posts.post', post_id=post.id) }}" class="link-info">Read More</a>
            {% endif %}
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('users.user_posts', username=user.username, page=page_num) }}">{{page_num}}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts', username=user.username, page=page_num) }}">{{page_num}}</a>
          {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

Projects/flask-blog/flaskblog/templates/users.html
{% extends 'layout.html' %}
{% block content %}
<h1 style="color:red">Admins</h1><hr>
{% for admin in admins %}
    <h5 class="{% if not loop.last %} mb-1 {% endif %}"><a href="{{url_for('users.user_posts', username=admin.username)}}">{{admin.username}}</a>
    {% if current_user.is_admin %}
      - <a href="mailto:{{admin.email}}">{{admin.email}}</a>
    {% endif %}
    </h5>
{% endfor %}
<hr>
<h1 style="color:gray">Users</h1><hr>
{% for user in users.items %}
    <h5 class="{% if not loop.last %} mb-1 {% endif %}"><a href="{{url_for('users.user_posts', username=user.username)}}">{{user.username}}</a>
    {% if current_user.is_admin %}
      - <a href="mailto:{{user.email}}">{{user.email}}</a>
    {% endif %}
    </h5>
{% endfor %}
{% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if users.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('users.users', page=page_num) }}">{{page_num}}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('users.users', page=page_num) }}">{{page_num}}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
    {% endfor %}
<hr>
{% endblock content %}