Projects/cointracker/cointracker/models.py
from cointracker import db


class Sparkline(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_updated = db.Column(db.Date, nullable=False)

    def __repr__(self):
        return f"Sparkline graph was last updated on'{self.date_updated}"

Projects/cointracker/cointracker/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from cointracker.config import Config
from flask_wtf.csrf import CSRFProtect

db = SQLAlchemy()
csrf = CSRFProtect()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    csrf.init_app(app)

    from cointracker.main.routes import main_bp
    from cointracker.exchanges.routes import exchanges_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(exchanges_bp)

    return app

Projects/cointracker/cointracker/exchanges/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from numerize import numerize
from ..utils import get_gecko, get_global_metrics

exchanges_bp = Blueprint('exchanges', __name__)


@exchanges_bp.route('/exchanges')
def exchanges():
    exchanges = get_gecko("https://api.coingecko.com/api/v3/exchanges?page=1")
    necessary_pairs = ["trust_score_rank", "trust_score",
                       "year_established", "name", "trade_volume_24h_btc", "image", "url", "country"]

    currency = 'usd'

    btc_price = get_gecko(
        f"https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies={currency}")['bitcoin'][currency]

    exchanges = [{k: v for k, v in exchange.items() if k in necessary_pairs}
                 for exchange in exchanges]

    for exchange in exchanges:
        exchange['trade_volume_24h'] = numerize.numerize(
            exchange['trade_volume_24h_btc'] * btc_price)
        exchange['url'] = "https://www.kraken.com/" if exchange['name'] == 'Kraken' else exchange['url']
        exchange['year_established'] = '2013' if exchange['name'] == 'Gate.io' else exchange['year_established']
        exchange['year_established'] = "—" if not exchange['year_established'] else exchange['year_established']

    return render_template('exchanges.html', global_metrics=get_global_metrics(), exchanges=exchanges)

Projects/cointracker/cointracker/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from cointracker.main.utils import draw_sparkline
import datetime
from cointracker import db
from cointracker.models import Sparkline
from cointracker.utils import get_cmc, get_eth_gas, get_gecko, get_global_metrics
from numerize import numerize

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
@main_bp.route('/home')
def home():


    coins = get_gecko(
        "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true&price_change_percentage=1h%2C24h%2C7d%2C30d")

    necessary_pairs = ["market_cap_rank", "current_price",
                       "name", "image", "symbol", "price_change_percentage_24h", "market_cap", "total_volume",
                       "ath", "sparkline_in_7d", "price_change_percentage_1h_in_currency", "price_change_percentage_7d_in_currency",
                       "price_change_percentage_30d_in_currency"
                       ]

    coins = [{k: v for k, v in coin.items() if k in necessary_pairs}
             for coin in coins]

    for coin in coins:
        coin['athcondition'] = True if coin['ath'] < coin['current_price'] else False
        if coin['athcondition']:
            coin['percent_ath'] = f"{(coin['current_price'] / coin['ath'] - 1)*100:.2f}"
        else:
            coin['percent_ath'] = f"{(1 - coin['current_price'] / coin['ath'])*100:.2f}"
        coin['market_cap'] = numerize.numerize(float(coin['market_cap']))
        coin['total_volume'] = numerize.numerize(float(coin['total_volume']))
        coin['symbol'] = coin['symbol'].upper()
        coin['current_price'] = f"{coin['current_price']:,.2f}" if coin[
            'current_price'] > 0.001 else f"{coin['current_price']:,.5f}"
        coin['ath'] = f"{coin['ath']:,}"
        coin['price_change_percentage_24h'] = f"{coin['price_change_percentage_24h']:.2f}"
        coin['price_change_percentage_1h_in_currency'] = f"{coin['price_change_percentage_1h_in_currency']:.2f}"
        coin['price_change_percentage_7d_in_currency'] = f"{coin['price_change_percentage_7d_in_currency']:.2f}"
        coin['price_change_percentage_30d_in_currency'] = f"{coin['price_change_percentage_30d_in_currency']:.2f}"

    sparkline_values = [i['sparkline_in_7d']['price'] for i in coins]
    q = Sparkline.query.all()
    if not q:
        draw_sparkline(sparkline_values)
        q = Sparkline(date_updated=datetime.datetime.now().date())
        db.session.add(q)
        db.session.commit()
    else:
        if q[0].date_updated != datetime.datetime.now().date():
            draw_sparkline(sparkline_values)
            q[0].date_updated = datetime.datetime.now().date()
            db.session.commit()

    return render_template('home.html', global_metrics=get_global_metrics(), coins=coins, sparkline_values=sparkline_values)


@ main_bp.route('/about')
def about():
    pass

Projects/cointracker/cointracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css">
    <title>CoinTracker - {% block title %}{% endblock title %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <div class="main-header">
        <div class="stats-tab">
            <div class="container">
                <div class="stats-list">
                    <ul>
                        <li>Cryptocurrencies: <a href="#">{{global_metrics[0]}}</a> </li>
                        <li>Exchanges: <a href="#">{{global_metrics[1]}}</a> </li>
                        <li>Market Cap: <a href="#">${{global_metrics[2]}}</a> </li>
                        <li>24h Vol: <a href="#">${{global_metrics[3]}}</a> </li>
                        <li>Dominance: <a href="#">BTC: {{global_metrics[4]}}% ETH: {{global_metrics[5]}}%</a> </li>
                        <li>ETH Gas: <a href="#">{{global_metrics[6]}} Gwei</a> </li>
                    </ul>
                </div>
                <div class="user-buttons">
                    <button><a href="#">Login</a></button>
                    <button><a href="#">Sign up</a></button>
                </div>
            </div>
        </div>
        <nav>
            <div class="nav-header">
                <img src="{{ url_for('static', filename='img/coin.png') }}" alt="Title Image">
                <a class="nav-title" title="Go to homepage" href="{{ url_for('main.home') }}">Coin Tracker</a>
            </div>
            <div class="nav-sections">
                <div class="sections-container">
                    <ul>
                        <li><a href="{{ url_for('main.home') }}">Cryptocurrencies</a></li>
                        <li><a href="{{ url_for('exchanges.exchanges') }}">Exchanges</a></li>
                        <li><a href="#">Mining Stats</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% block content %}{% endblock content %}
</body>
</html>

Projects/cointracker/cointracker/templates/exchanges.html
{% extends 'base.html' %}
{% block title %}Exchanges{% endblock title %}

{% block content %}

<div class="main-body">
    <div class="body-nav container">
        <div class="body-nav-btns">
            <h1><i class="fa-solid fa-coins"></i> Top Exchanges by Trade Volume</h1>
        </div>
    </div>
    <div class="exchanges-tab">
        <table class="exchanges-table">
            <tr>
                <th>#</th>
                <th style="text-align:left">Exchange</th>
                <th>Year Established</th>
                <th>Trust Score</th>
                <th>24h Trade Volume</th>
            </tr>
            {% for exchange in exchanges %}
                <tr>
                    <td class="exchange-item" style="padding-left:1%">{{exchange.trust_score_rank}}</td>
                    <td class="exchange-item" style="text-align:left;"><a href="{{exchange.url}}"><img src="{{exchange.image}}" alt="{{exchange.name}}">{{exchange.name}}</a></td>
                    <td class="exchange-item" style="padding-left:0%; padding-right:0%">{{exchange.year_established}}</td>
                    <td class="exchange-item">{{exchange.trust_score}}/10</td>
                    <td class="exchange-item">${{exchange.trade_volume_24h}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock content %}

Projects/cointracker/cointracker/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="main-body">
    <div class="body-nav container">
        <div class="body-nav-btns">
            <h1><i class="fa-brands fa-bitcoin"></i>  Top Cryptocurrencies by Market Cap</h1>
            <br>
            <a href="#"><button><i class="fa-solid fa-star" style="margin-right:5px"></i>Watchlist</button></a>
            <a href="#"><button><i class="fa-brands fa-space-awesome" style="margin-right:5px"></i>Top Coins by Categories</button></a>
        </div>
    </div>
    <div class="coins-tab">
        <table class="coins-table">
            <tr>
                <th>#</th>
                <th style="text-align:left">Name</th>
                <th>Price</th>
                <th>24h %</th>
                <th>30d %</th>
                <th>Market Cap</th>
                <th>Volume(24h)</th>
                <th>All Time High (ATH)</th>
                <th>Last 7 Days</th>
            </tr>
            {% for coin in coins %}
                <tr>
                    <td class="coin-item" style="padding-left:1%">{{ coin.market_cap_rank }}</td>
                    <td class="coin-item" style="text-align:left"> <img src="{{coin.image}}" alt="Coin Image"> {{ coin.name }} <span class="text-muted">{{coin.symbol}}</span></td>
                    <td class="coin-item">${{ coin.current_price }}</td>

                    <td class="coin-item">
                        {% if "-" in coin.price_change_percentage_24h %}
                            <i class="fa-solid fa-caret-down"></i><span style="color:rgb(237,83,92)"> {{ coin.price_change_percentage_24h }}%</span>
                        {% else %}
                            <i class="fa-solid fa-caret-up"></i><span style="color:rgb(63,209,154)"> {{ coin.price_change_percentage_24h }}%</span>
                        {% endif %}
                    </td>
                    <td class="coin-item">
                        {% if "-" in coin.price_change_percentage_30d_in_currency %}
                            <i class="fa-solid fa-caret-down"></i><span style="color:rgb(237,83,92)"> {{ coin.price_change_percentage_30d_in_currency }}%</span>
                        {% else %}
                            <i class="fa-solid fa-caret-up"></i><span style="color:rgb(63,209,154)"> {{ coin.price_change_percentage_30d_in_currency }}%</span>
                        {% endif %}
                    </td>
                    <td class="coin-item">${{ coin.market_cap }}</td>
                    <td class="coin-item">${{ coin.total_volume }}</td>
                    <td class="coin-item">${{ coin.ath }}
                        <p>
                            {% if coin.athcondition %}
                            <span style="color:rgb(63,209,154)">{{coin.symbol}} is currently {{coin.percent_ath}}% above it's ATH.</span>
                            {% else %}
                            <span style="color:rgb(237,83,92)">{{coin.symbol}} is currently {{coin.percent_ath}}% below it's ATH.</span>
                            {% endif %}
                        </p>
                    </td>
                    <td class="coin-item">
                        <!-- <canvas id="lineChart-{{coin.market_cap_rank}}" width="164" height="48"></canvas> -->
                        {% set file = 'img/sparkline'+loop.index|string+'.png' %}
                        <img class="sparkline" src="{{ url_for('static', filename=file) }}" alt="">
                        <meta id="sparkline_vals" data-playlist="{{ sparkline_values[coin.market_cap_rank-1] }}">
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock content %}